### ISSUE TITLE
Dining Design Revamp

### ISSUE THREAD

**Issue by eureika** [pennlabs/penn-mobile-android#325]
![dining](https://cloud.githubusercontent.com/assets/11711483/12869311/34fec7d0-cce9-11e5-9655-28f1b8bab669.jpg)
![dining_grid](https://cloud.githubusercontent.com/assets/11711483/12869312/34ff813e-cce9-11e5-9a2f-b05e835ed22d.jpg)

**Comment by adelq** [comment]
Comments:
* I really like the all caps "open"/"closed", but don't understand the logic behind the vertical placement of it.
* Also, the row with Accenture Cafe should be small to fit. 
* In the same vein, all halls should have the arrow, ones with meals get the menus and others get the info, I like this.
* I don't like the descriptions being so light gray, reading in sunlight/nonideal conditions will be difficult.

Sidenote: when did we choose maize to be our secondary color? Didn't know we were going for a University of Michigan colorscheme

**Comment by eureika** [comment]
Responses:
- Vertical alignment because less cluttered and avoids odd placement of open/closed sign with >
- I personally think the small fit doesn't look nice, mainly because it affects the look of everything else as well. Especially because this page has a bright red and green sign, if you have one with a different card size, it would look a little odd if it's not uniform.
- I made a new issues that deals with combining hours + menus together, so we don't have mixed icons of arrows and info.
- We could definitely change the text color.
- I randomly picked one (Amber) and thought it looked nice and went well with blue. We could choose something else from material design.

**Comment by adelq** [comment]
* Yes, definitely should be on the same vertical alignment as >, I concede :smile: 
* This shouldn't be a problem in the real world since all dining halls should always have hours
* :+1: 
* :+1: 
* We should choose something else, I was thinking maybe pink? to keep somewhat consistent with Penn color schemes but be a little more distinctive and bright

**Comment by eureika** [comment]
Ohhh Pink sounds great. Just thought I'd get more opposition if I chose that... haha

**Comment by lilyidi** [comment]
Is this okay?
![screenshot_2016-03-14-22-28-38 1](https://cloud.githubusercontent.com/assets/9397415/13765960/52f8c55c-ea34-11e5-8455-034fffc796bc.png)

(I made the Open/Close indicator and arrow on the same line as the name of the dining hall) 
Otherwise, if I make them centered vertically, the next open meal and the sign may overlap:
![screenshot_2016-03-14-22-32-28](https://cloud.githubusercontent.com/assets/9397415/13766042/e4d1741a-ea34-11e5-992d-fec6b7a67264.png)

**Comment by lilyidi** [comment]
@eureika This is what it looks like now:
![screenshot_2016-03-21-21-04-19](https://cloud.githubusercontent.com/assets/9397415/13939194/376596ba-efa9-11e5-9440-04a23992e2b3.png)
![screenshot_2016-03-21-21-03-46](https://cloud.githubusercontent.com/assets/9397415/13939193/376542f0-efa9-11e5-9f73-3e37cf047c07.png)

**Comment by eureika** [comment]
Changes to make:
- Background color to #FAFAFA
- Closed/Open to smaller font size (30pt relative to current 42pt) but all caps
- Closed/Open icon both should have same width
- Check font sizes - Dining Hall/Cafe names are way too big
