### ISSUE TITLE
Back on Laundry Fragment does not work properly

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#404]
Steps to reproduce:
1. Open laundry list of halls fragment
2. Open a residential hall
3. Press back (doesn't matter if hardware/software back or the Toolbar back)

Expected: Goes back to listing of laundry halls
Bug: Goes to (I think) the first residential hall you opened

**Comment by jasontsh** [comment]
Can't reproduce.

**Comment by adelq** [comment]
I cannot reproduce right now with a freshly launched app, but I was able to reliably reproduce it earlier. The tabs are definitely not handled properly when navigating away from laundry.

**Comment by jasontsh** [comment]
I believe you. I sometimes have this as well I think.  I think what happened is that in onResume the tabs stayed but the app goes back to home page or something. Maybe we can do a check for onResume and probably onRestart. I'll let @andrewsi10  look into it.

**Comment by andrewsi10** [comment]
Managed to reproduce the bug - or at least a very similar one. Steps:

1. Go to list of laundry halls
2. Open one of the residential halls (hall A).
3. Open side bar and select laundry.
4. Open a residential hall (hall B).
5. Press back, and the app will go to hall A instead of the list of laundry halls.

**Comment by andrewsi10** [comment]
Release 1.14.0 changed the UI for laundry, so this issue is no longer present. https://github.com/pennlabs/penn-mobile-android/releases/tag/v1.14.0
